# Generated by Django 5.2.3 on 2026-06-10 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disbursement_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='loans.loanrequest')),
            ],
        ),
    ]
